# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
plugins:
  - jekyll-datapage-generator
  
# Site settings
title: RHAD Lab
email: rachel.bouserhal@etsmtl.ca
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: ""

include:
  - .htaccess
  - _pages


sass:
  sass_dir: _sass


site:
  site_dir: _site

page_gen-dirs: true # uncomment, if you prefer to generate named folders

page_gen:
  - data: 'projects'
    template: 'project'
    name: 'url'
    dir: 'projects'


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
plugins:
  - jekyll-redirect-from
# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links



    
